#! /bin/bash

# Source the github-boxen bits
source /opt/boxen/env.sh

# Set the bash prompt ($PS1)
source .script/prompt.sh
set_prompt

# Setup aliases
source .script/aliases.sh

# Source bash completion stuff (SLOOOOOOOWWWW)
source `brew --prefix`/etc/bash_completion
