#! /bin/bash

for sh in .script/*.sh ; do
  source $sh
done

# Set the bash prompt ($PS1)
PROMPT_COMMAND=set_prompt

# Source bash completion stuff (SLOOOOOOOWWWW)
source `brew --prefix`/etc/bash_completion
